server {
    listen 80;

    root /var/www/html/src/public;
    index routeur.php index.php;

    location / {
        try_files $uri $uri/ /routeur.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass php:9000;

        fastcgi_index routeur.php;

        fastcgi_param SCRIPT_FILENAME /var/www/html/src/public$fastcgi_script_name;
    }
}